### ISSUE TITLE
Integration in HomeGenie software.

### ISSUE THREAD

**Issue by genielabs** [abelsilva/knx.net#2]
Just to let you know I integrated your library in https://github.com/genielabs/HomeGenie .
As I don't have any knx hardware can't tell if it's working like it should. Hope you like it.
Kind regards,
Gene.

**Comment by abelsilva** [comment]
sure, I'm glad it is useful for you

If you want, you might try to use eibd to do some tests
https://www.auto.tuwien.ac.at/~mkoegler/index.php/eibd

It allows you to emulate a KNX IP Router (Routing connection) or KNX IP Interface (Tunneling connection)

cheers
abel
